### ISSUE TITLE
Coin type serialization

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-core#13]
[Bip44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) proposes the `Registered coin types` which are defined in [slip44](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)

Of interest:

| index |       hexa | symbol | coin                |
|-------|------------|--------|---------------------|
|   128 | 0x80000080 | XMR    | Monero              |
|     0 | 0x80000000 | BTC    | Bitcoin             |
|     1 | 0x80000001 |        | Testnet (all coins) |

We should distinguish the testnets for the encoding

**Comment by h4sh3d** [comment]
It's a good starting point, but as you mentioned the 'all testnet coins' is quite annoying as we still have to distinguish the two assets on the offer.

The design I'm leaning for is:
```rust
pub enum Network {
    Mainnet,
    Testnet,
}

pub struct Offer<Ar, Ac> where ... {
    network: Network,
    ar: Ar,
    ac: Ac,
    ...
}
```
with a serialization of a network flag and the two coins as defined in SLIP44 mainnet.
