### ISSUE TITLE
impl txid and txlabel functions for Transaction

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-core#155]

**Comment by h4sh3d** [comment]
Label can be retrieved with `get_id(&self) -> TxLabel` with is implemented on traits like `Buyable`, `Cancelable`, etc.

TxId is not a known type is the current system. We have to use `Transation::as_partial()` to get, e.g. with Bitcoin, a PSBT to then call the txid or wtxid.

**Comment by h4sh3d** [comment]
`get_id(&self) -> TxLabel` should be renamed into `get_label` instead.
