### ISSUE TITLE
SwapId info using swap-cli

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-core#92]
`swap0-cli info`

returns 

```
swaps:
  - "0xc706…17db"
```

To query info about a specific swap, swap-cli needs complete SwapId to make the call

**Comment by h4sh3d** [comment]
Uhm, that’s the default implementation of Display with the macro, it is “user friendly” but does works for us obviously. I’ll see how to change that.

**Comment by h4sh3d** [comment]
Resolved in node.
